name: AWS DEPLOY TO STAGING

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    env:
      VUE_APP_CLIENT_ID: ${{secrets.VUE_APP_CLIENT_ID}}
      VUE_APP_API_URL: ${{secrets.VUE_APP_API_URL}}
      VUE_APP_CLIENT_URL: ${{secrets.VUE_APP_CLIENT_URL}}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          touch .env
          echo VUE_APP_CLIENT_ID="$VUE_APP_CLIENT_ID" >> .env
          echo VUE_APP_API_URL="$VUE_APP_API_URL" >> .env
          echo VUE_APP_CLIENT_URL=tutorial.eaglesoftwareteam.com >> .env
          echo VUE_APP_SITE_URL=tutorial.eaglesoftwareteam.com >> .env

      - run: npm install
      - run: npm run build
      - run: npm run bundle

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: "tutorial.eaglesoftwareteam.com"
          REMOTE_USER: ubuntu
          TARGET: "/var/www/html/tutorial-frontend-vue2"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: 16.x

      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          VUE_APP_CLIENT_ID: ${{secrets.VUE_APP_CLIENT_ID}}
          VUE_APP_API_URL: ${{secrets.VUE_APP_API_URL}}
          VUE_APP_CLIENT_URL: https://tutorial.eaglesoftwareteam.com
          VUE_APP_CLIENT_SECRET: ${{secrets.VUE_APP_CLIENT_SECRET}}
          VUE_APP_REFRESH_TOKEN: ${{secrets.VUE_APP_REFRESH_TOKEN}}
        with:
          build: npx cypress info
          config: baseUrl=https://tutorial.eaglesoftwareteam.com
          headed: true
